### ISSUE TITLE
Crash on Order Rejection on Insufficient Funds

### ISSUE THREAD

**Issue by gavincyi** [Aurora-Team/Bitzkrieg#14]
2017-05-10 14:31:29,757 - INFO 
[IN]
{'responseStatus': {'errorCode': '1005', 'message': 'Insufficient funds'}}

Traceback (most recent call last):
  File "/usr/local/bin/bitz", line 11, in <module>
    load_entry_point('Bitzkrieg==0.0.1', 'console_scripts', 'bitz')()
  File "/usr/local/lib/python3.5/dist-packages/bitz/bitzkrieg.py", line 54, in main
    strategy.monitor()
  File "/usr/local/lib/python3.5/dist-packages/bitz/single_market_making.py", line 355, in monitor
    fix_responses, err_text = self.ordsvr.request(sell_order)
  File "/usr/local/lib/python3.5/dist-packages/bitz/order_server.py", line 119, in request
    responses, err = exchange.request(req)
  File "/usr/local/lib/python3.5/dist-packages/bitz/exch_gatecoin_eis.py", line 70, in request
    if err_code >= 100:
TypeError: unorderable types: str() >= int()
Exception ignored in: <bound method InternalJournalDatabase.__del__ of <bitz.journal_database.InternalJournalDatabase object at 0x7f43d23a1f28>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bitz/journal_database.py", line 59, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method InternalRealtimeDatabase.__del__ of <bitz.realtime_database.InternalRealtimeDatabase object at 0x7f43d23a1ef0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bitz/realtime_database.py", line 61, in __del__

**Comment by gavincyi** [comment]
Not seen again.
