### ISSUE TITLE
Crash on failed request

### ISSUE THREAD

**Issue by gavincyi** [Aurora-Team/Bitzkrieg#15]
Run job 59.

2017-05-14 08:38:35,817 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders
data={"Way": "Bid", "Price": 14126.01, "Code": "BTCHKD", "Amount": 0.00353}
headers={'API_REQUEST_DATE': '1494751115.8170455', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'i5ci+6c4IhI/2Wy0tSdHsLmbonjRjGn85bGlGISYIjQ='}

2017-05-14 08:38:35,966 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'clOrderId': 'BK11491285966'}

2017-05-14 08:38:35,982 - INFO 
[SingleMarketMaking]
Order is opened.
{'OrderQtyData': {'OrderQty': 0.00353}, 'ExecID': '20170514T08:38:35.9786225c8d5b2c-73a8-4e4c-aabd-af574f514c60', 'TransactTime': datetime.datetime(2017, 5, 14, 8, 38, 35, 978476), 'ExecType': '0', 'CumQty': 0, 'Price': 14126.01, 'OrdType': '2', 'OrderID': 'BK11491285966', 'ClOrdID': '20170514T08:38:35.806021a899f1db-5293-4de8-9ffa-e2c0b0d068a8', 'Instrument': {'Symbol': 'BTCHKD', 'SecurityExchange': 'Gatecoin'}, 'Header': {'MsgType': '8'}, 'LeavesQty': 0.00353, 'OrdStatus': '0', 'Side': '1'}

2017-05-14 08:38:36,849 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491285966
data={"clOrderId": "BK11491285966"}
headers={'API_REQUEST_DATE': '1494751116.849083', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'BZOQzinBkI3RQH4Jr7kWAtAMF2u/5C8wQyD6q1DVgIM='}

2017-05-14 08:38:36,975 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'initialQuantity': 0.00353, 'code': 'BTCHKD', 'date': '1494751116', 'statusDesc': 'New', 'clOrderId': 'BK11491285966', 'side': 0, 'tranSeqNo': 1855008, 'type': 0, 'status': 1, 'remainingQuantity': 0.00353, 'price': 14126.01}}

2017-05-14 08:40:32,724 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders
data={"Way": "Ask", "Price": 14384.9899, "Code": "BTCHKD", "Amount": 0.0034700000000000004}
headers={'API_REQUEST_DATE': '1494751232.7243528', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'63T7oykQ8M+BGd/JsRuUIv1SKgpTuniYV7GeEZl7l3Y='}

2017-05-14 08:40:32,878 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'clOrderId': 'BK11491285981'}

2017-05-14 08:40:32,885 - INFO 
[SingleMarketMaking]
Order is opened.
{'OrderQtyData': {'OrderQty': 0.0034700000000000004}, 'ExecID': '20170514T08:40:32.883102704c738b-91f9-41cd-9cb9-49c85f2edf34', 'TransactTime': datetime.datetime(2017, 5, 14, 8, 40, 32, 883005), 'ExecType': '0', 'CumQty': 0, 'Price': 14384.9899, 'OrdType': '2', 'OrderID': 'BK11491285981', 'ClOrdID': '20170514T08:40:32.721973746b5b7d-1309-4135-8271-36941263c4b7', 'Instrument': {'Symbol': 'BTCHKD', 'SecurityExchange': 'Gatecoin'}, 'Header': {'MsgType': '8'}, 'LeavesQty': 0.0034700000000000004, 'OrdStatus': '0', 'Side': '2'}

2017-05-14 08:41:25,908 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491285966
data={"clOrderId": "BK11491285966"}
headers={'API_REQUEST_DATE': '1494751285.9081671', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'ET0ntx6uwt/I9/ZUgy+fWRElstCxi7nii798NKuZN2M='}

2017-05-14 08:41:26,049 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'initialQuantity': 0.00353, 'code': 'BTCHKD', 'date': '1494751116', 'statusDesc': 'New', 'clOrderId': 'BK11491285966', 'side': 0, 'tranSeqNo': 1855008, 'type': 0, 'status': 1, 'remainingQuantity': 0.00353, 'price': 14126.01}}

2017-05-14 08:41:26,057 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491285981
data={"clOrderId": "BK11491285981"}
headers={'API_REQUEST_DATE': '1494751286.0572655', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'TPLk5U7fvy/HtlDM4z3JWfvNNykjLdzjn7d8jFFFf0E='}

2017-05-14 08:41:26,190 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'initialQuantity': 0.00347, 'code': 'BTCHKD', 'date': '1494751233', 'statusDesc': 'New', 'clOrderId': 'BK11491285981', 'side': 1, 'tranSeqNo': 1855022, 'type': 0, 'status': 1, 'remainingQuantity': 0.00347, 'price': 14384.9899}}

2017-05-14 08:50:29,897 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491285966
data={"clOrderId": "BK11491285966"}
headers={'API_REQUEST_DATE': '1494751829.896799', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'IVaAZnave3e8j0f6cBoqAgna/weuYZ+e2t5reYFfGMU='}

2017-05-14 08:52:37,146 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'initialQuantity': 0.00353, 'code': 'BTCHKD', 'date': '1494751116', 'statusDesc': 'New', 'clOrderId': 'BK11491285966', 'side': 0, 'tranSeqNo': 1855008, 'type': 0, 'status': 1, 'remainingQuantity': 0.00353, 'price': 14126.01}}

2017-05-14 08:52:37,151 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491285981
data={"clOrderId": "BK11491285981"}
headers={'API_REQUEST_DATE': '1494751957.1513855', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'pAtt2tFSrMtWVcrLxWTDBRBwvZRrJVvhuJP9oWQxDAs='}

2017-05-14 08:52:37,200 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'initialQuantity': 0.00347, 'code': 'BTCHKD', 'date': '1494751233', 'statusDesc': 'Executed', 'clOrderId': 'BK11491285981', 'side': 1, 'tranSeqNo': 1855088, 'type': 0, 'status': 6, 'remainingQuantity': 0, 'price': 14384.9899}}

2017-05-14 08:52:37,202 - INFO 
[SingleMarketMaking]
Order is fully filled.
Filled volume = 0.0035.
{'OrderQtyData': {'OrderQty': 0.00347}, 'ExecID': '20170514T08:52:37.2018260c916f7a-5ab5-4a1c-b74b-065de16c3cf6', 'TransactTime': datetime.datetime(2017, 5, 14, 8, 52, 37, 201790), 'AvgPx': 14384.9899, 'CumQty': 0.00347, 'ExecType': 'I', 'OrdType': '2', 'OrderID': 'BK11491285981', 'LeavesQty': 0, 'Instrument': {'Symbol': 'BTCHKD', 'SecurityExchange': 'Gatecoin'}, 'Header': {'MsgType': '8'}, 'Price': 14384.9899, 'OrdStatus': '2', 'Side': '2'}

2017-05-14 08:52:37,204 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders
data={"Way": "Ask", "Price": 14384.9899, "Code": "BTCHKD", "Amount": 0.0034700000000000004}
headers={'API_REQUEST_DATE': '1494751957.2039685', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'nZTQvdlV8QRI/eu6nWF6kzfCo3vyUtiLz0BmTiNlyaM='}

2017-05-14 08:52:37,290 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'clOrderId': 'BK11491286061'}

2017-05-14 08:52:37,292 - INFO 
[SingleMarketMaking]
Order is opened.
{'OrderQtyData': {'OrderQty': 0.0034700000000000004}, 'ExecID': '20170514T08:52:37.2915718af680e8-a070-4274-b34f-4d346f07c6a4', 'TransactTime': datetime.datetime(2017, 5, 14, 8, 52, 37, 291525), 'ExecType': '0', 'CumQty': 0, 'Price': 14384.9899, 'OrdType': '2', 'OrderID': 'BK11491286061', 'ClOrdID': '20170514T08:52:37.20345688a7d70b-8a30-47a3-a2a2-ad977635d5b2', 'Instrument': {'Symbol': 'BTCHKD', 'SecurityExchange': 'Gatecoin'}, 'Header': {'MsgType': '8'}, 'LeavesQty': 0.0034700000000000004, 'OrdStatus': '0', 'Side': '2'}

2017-05-14 08:53:08,514 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491285966
data={"clOrderId": "BK11491285966"}
headers={'API_REQUEST_DATE': '1494751988.5142646', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'mFYS9TmkPWlAZEg67D9LEvYqMJbammd5HLSvEaD6Cb4='}

2017-05-14 08:53:08,596 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'initialQuantity': 0.00353, 'code': 'BTCHKD', 'date': '1494751116', 'statusDesc': 'New', 'clOrderId': 'BK11491285966', 'side': 0, 'tranSeqNo': 1855008, 'type': 0, 'status': 1, 'remainingQuantity': 0.00353, 'price': 14126.01}}

2017-05-14 08:53:08,602 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491286061
data={"clOrderId": "BK11491286061"}
headers={'API_REQUEST_DATE': '1494751988.602549', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_SIGNATURE': b'Nw4a7oYe7ddK5nLv6a5q4rkD1PHz0ATKIt8e1+jOSjQ='}

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/ssl_.py", line 325, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bitz", line 11, in <module>
    load_entry_point('Bitzkrieg==0.0.1', 'console_scripts', 'bitz')()
  File "/usr/local/lib/python3.5/dist-packages/bitz/bitzkrieg.py", line 54, in main
    strategy.monitor()
  File "/usr/local/lib/python3.5/dist-packages/bitz/single_market_making.py", line 124, in monitor
    fix_responses, err_text = self.ordsvr.request(order_status_request)
  File "/usr/local/lib/python3.5/dist-packages/bitz/order_server.py", line 119, in request
    responses, err = exchange.request(req)
  File "/usr/local/lib/python3.5/dist-packages/bitz/exch_gatecoin_eis.py", line 117, in request
    response = self.request_order_status_request(req)
  File "/usr/local/lib/python3.5/dist-packages/bitz/exch_gatecoin_eis.py", line 217, in request_order_status_request
    return self.eig.send_request("Trade/Orders/%s" % req.OrderID.value, "GET", param)
  File "/usr/local/lib/python3.5/dist-packages/bitz/exch_gatecoin_eig.py", line 64, in send_request
    response = R(url, data=data, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by gavincyi** [comment]
Not seen crashed again.
