### ISSUE TITLE
Record Not Exist

### ISSUE THREAD

**Issue by gavincyi** [Aurora-Team/Bitzkrieg#16]
Run job 58

2017-05-14 06:46:39,987 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491283895
data={"clOrderId": "BK11491283895"}
headers={'API_REQUEST_SIGNATURE': b'g5o/7vnK9sxkfC1w3q5xvzBRHNgVDFsroMAe85w3OE8=', 'API_REQUEST_DATE': '1494744399.9866498', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I'}

2017-05-14 06:46:40,130 - INFO 
[IN]
{'order': {'price': 13900.01, 'clOrderId': 'BK11491283895', 'status': 1, 'date': '1494743744', 'statusDesc': 'New', 'tranSeqNo': 1853202, 'code': 'BTCHKD', 'side': 0, 'initialQuantity': 0.00359, 'type': 0, 'remainingQuantity': 0.00359}, 'responseStatus': {'message': 'OK'}}

2017-05-14 06:46:40,151 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491283896
data={"clOrderId": "BK11491283896"}
headers={'API_REQUEST_SIGNATURE': b'zO7QE4koE9lUEtG7ntpWWZVbLlF2APAkAiU1+jdw07U=', 'API_REQUEST_DATE': '1494744400.1510556', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I'}

2017-05-14 06:46:40,274 - INFO 
[IN]
{'order': {'price': 14234.99, 'clOrderId': 'BK11491283896', 'status': 1, 'date': '1494743744', 'statusDesc': 'New', 'tranSeqNo': 1853203, 'code': 'BTCHKD', 'side': 1, 'initialQuantity': 0.00351, 'type': 0, 'remainingQuantity': 0.00351}, 'responseStatus': {'message': 'OK'}}

2017-05-14 06:46:40,287 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders
data={"clOrderId": "BK11491283896"}
headers={'API_REQUEST_SIGNATURE': b'GqT1zZPLwKBOmQNsfEwjS578iM/d5WTcMtMbzrz9dpI=', 'API_REQUEST_DATE': '1494744400.2869146', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I'}

2017-05-14 06:46:40,472 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}}

2017-05-14 06:46:40,477 - INFO 
[SingleMarketMaking]
Cancel is accepted.
{'OrderID': 'BK11491283896', 'OrdStatus': '4', 'OrderQtyData': {'OrderQty': 0.00351}, 'Side': '2', 'ExecType': '4', 'Header': {'MsgType': '8'}, 'ExecID': '20170514T06:46:40.475020e9f358b3-746f-459b-8781-c5f2ad33db98', 'ClOrdID': '20170514T06:46:40.2793750cb1a8aa-4d71-4520-978b-996f802f1604', 'Instrument': {'SecurityExchange': 'Gatecoin', 'Symbol': 'BTCHKD'}, 'LeavesQty': 0, 'Price': 14234.99, 'CumQty': 0.0, 'TransactTime': datetime.datetime(2017, 5, 14, 6, 46, 40, 474882)}

2017-05-14 06:46:41,021 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491283895
data={"clOrderId": "BK11491283895"}
headers={'API_REQUEST_SIGNATURE': b'hgRSfVxtza8fLzIEjW1LBbcYPkKL6pAHuA2dP9Xl0Mk=', 'API_REQUEST_DATE': '1494744401.0217698', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I'}

2017-05-14 06:46:41,134 - INFO 
[IN]
{'order': {'price': 13900.01, 'clOrderId': 'BK11491284109', 'status': 4, 'date': '1494743744', 'statusDesc': 'Cancelled', 'tranSeqNo': 1853400, 'code': 'BTCHKD', 'side': 0, 'initialQuantity': 0.00359, 'type': 0, 'remainingQuantity': 0.00359}, 'responseStatus': {'message': 'OK'}}

2017-05-14 06:49:11,135 - INFO 
[OUT]
url=https://api.gatecoin.com/Trade/Orders/BK11491284109
data={"clOrderId": "BK11491284109"}
headers={'API_REQUEST_SIGNATURE': b'BfmrrnDGlmWDzqDdFnl/gZhElWtZy0jkzXK9+v6Awj4=', 'API_REQUEST_DATE': '1494744551.1348064', 'Content-Type': 'application/json', 'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I'}

2017-05-14 06:49:11,229 - INFO 
[IN]
{'responseStatus': {'errorCode': '1021', 'message': 'Record does not exist'}}

Traceback (most recent call last):
  File "/usr/local/bin/bitz", line 11, in <module>
    load_entry_point('Bitzkrieg==0.0.1', 'console_scripts', 'bitz')()
  File "/usr/local/lib/python3.5/dist-packages/bitz/bitzkrieg.py", line 54, in main
    strategy.monitor()
  File "/usr/local/lib/python3.5/dist-packages/bitz/single_market_making.py", line 126, in monitor
    assert len(fix_responses) == 1, "Unexpected number of messages (%d)" % len(fix_responses)
AssertionError: Unexpected number of messages (0)
Exception ignored in: <bound method InternalJournalDatabase.__del__ of <bitz.journal_database.InternalJournalDatabase object at 0x7f24eead0ef0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bitz/journal_database.py", line 59, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method InternalRealtimeDatabase.__del__ of <bitz.realtime_database.InternalRealtimeDatabase object at 0x7f24eead0eb8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bitz/realtime_database.py", line 61, in __del__
NameError: name 'open' is not defined
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by gavincyi** [comment]
Seems like an exchange issue. It happened again.

2017-05-17 12:30:41,087 - INFO 
[OUT]
method=GET
url=https://api.gatecoin.com/Trade/Orders/BK11491385044
data={"clOrderId": "BK11491385044"}
headers={'API_PUBLIC_KEY': 'nvUabzzxnlUUM9iX63Sd3R3W0EpIJQ5I', 'API_REQUEST_DATE': '1495024241.0874403', 'Content-Type': 'application/json', 'API_REQUEST_SIGNATURE': b'6OMB66cWHO63uMumfZeRm9Qh73NDVIgVXTQ+wlkIedA='}



2017-05-17 12:30:41,160 - INFO 
[IN]
{'responseStatus': {'message': 'OK'}, 'order': {'type': 0, 'code': 'BTCHKD', 'clOrderId': 'BK11491385277', 'initialQuantity': 0.00332, 'date': '1495023605', 'price': 15056.99, 'side': 1, 'remainingQuantity': 0.00332, 'status': 4, 'statusDesc': 'Cancelled', 'tranSeqNo': 1937398}}

**Comment by gavincyi** [comment]
Provided order ID during deletion.
